#!/bin/bash

echo "Start $0 ..."
get_fbdev=`grep -rnw /etc/X11/xorg.conf -e "/dev"`
fbdev=${get_fbdev//\"}
if [ "${fbdev:38}" == "fb0" ]; then
	echo "You are already on HDMI"
elif [ "${fbdev:38}" == "fb1" ]; then
	echo "Switching to HDMI..."
	sed -i 's/fb1/fb0/g' /etc/X11/xorg.conf
	echo "Rebooting ..."
	reboot
fi
